apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rvrg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-rvrg
    app.kubernetes.io/part-of: my-application
  name: devfile-sample-code-with-quarkus-rvrg
  namespace: beaumorley-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rvrg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-rvrg
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:c49787b4618b4c7da427bc86ee99bc1a20d42e32e1329c3fe85cc4d83fdc49f1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
