apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-vmcy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-vmcy
    app.kubernetes.io/part-of: my-application
  name: devfile-sample-code-with-quarkus-vmcy
  namespace: beaumorley-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-vmcy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-vmcy
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:64dae131b44962ea6f75cab7024dee36378368ccde24657df9f7980f1d175864
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
