apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-i62f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-i62f
    app.kubernetes.io/part-of: my-application
  name: devfile-sample-java-springboot-basic-i62f
  namespace: beaumorley-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-i62f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-i62f
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:345d778487e9dc738071341dc6bcb536114aeba5dee03ab02bee022ce5a4c7a8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
