apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-vmcy
  namespace: beaumorley-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:64dae131b44962ea6f75cab7024dee36378368ccde24657df9f7980f1d175864
        name: container-image
        resources: {}
status: {}
